### ISSUE TITLE
Running container creates __pycache__ folders as root

### ISSUE THREAD

**Issue by floatovh** [ovh/docs-rendering#361]
Hello,

Running the container is creating some "__pycache__" folders as root :
```
$ ls -l plugins/* | grep pycache
drwxr-xr-x 2 root root 4.0K Nov 30 12:57 __pycache__
drwxr-xr-x 2 root root 4.0K Nov 30 12:57 __pycache__
drwxr-xr-x 2 root root 4.0K Nov 30 12:57 __pycache__
```

**Comment by tbourrelovh** [comment]
Hello, thanks for the issue report. Could you please checkout on the branch `fix/docker-permissions`, rebuild the image and then rerun the project.

To build the image you should use the helper script `docker/build.sh`, as it will pass you user id and group to docker on build time

**Comment by floatovh** [comment]
Hello @tbourrelovh,

This branch fix the permission issue and no side effects encountered, thx.

**Comment by tbourrelovh** [comment]
Hello @floatovh, the issue should now be fixed on master & develop :slightly_smiling_face:
